const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { prepare, verify } = require('../../scripts/release/version.cjs');
test('prepare/verify enforce clean increasing versions, lockfile, tag and master ancestry', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lsaudio-version-'));
  const cwd = process.cwd(); process.chdir(root);
  t.after(() => { process.chdir(cwd); fs.rmSync(root, { recursive: true, force: true }); });
  const git = (...args) => execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init', '--initial-branch=master'); git('config', 'user.email', 'test@example.invalid'); git('config', 'user.name', 'Release tests');
  fs.writeFileSync('package.json', JSON.stringify({ version: '1.1.4' }));
  fs.writeFileSync('package-lock.json', JSON.stringify({ version: '1.1.4', packages: { '': { version: '1.1.4' } } }));
  git('add', '.'); git('commit', '-m', 'baseline');
  assert.throws(() => prepare('1.1.3'), /increase/);
  prepare('1.2.0-beta.1');
  assert.equal(JSON.parse(fs.readFileSync('package.json')).version, '1.2.0-beta.1');
  assert.throws(() => verify(), /unfinished/);
  assert.throws(() => prepare('1.2.0'), /clean/);
  fs.writeFileSync('CHANGELOG.md', fs.readFileSync('CHANGELOG.md', 'utf8').replaceAll('待填写', '已记录'));
  assert.equal(verify(), '1.2.0-beta.1');
  git('add', '.'); git('commit', '-m', 'version'); git('tag', 'v1.2.0-beta.1');
  assert.equal(verify({ tag: 'v1.2.0-beta.1', master: 'master' }), '1.2.0-beta.1');
  assert.throws(() => verify({ tag: 'v1.2.0', master: 'master' }), /mismatch/);
  git('checkout', '-b', 'unmerged'); prepare('1.2.0');
  fs.writeFileSync('CHANGELOG.md', fs.readFileSync('CHANGELOG.md', 'utf8').replaceAll('待填写', '已记录'));
  git('add', '.'); git('commit', '-m', 'not merged'); git('tag', 'v1.2.0');
  assert.throws(() => verify({ tag: 'v1.2.0', master: 'master' }));
  const lock = JSON.parse(fs.readFileSync('package-lock.json')); lock.version = '1.0.0'; fs.writeFileSync('package-lock.json', JSON.stringify(lock));
  assert.throws(() => verify(), /Lockfile/);
});
