// Reproducible, explicit vendor refresh; never run during ordinary builds.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const revision = '3a04f817a4380c00ff51f9bcdc6c4e4bb7a18b80'; // CMSIS-DSP v1.14.4 commit
const base = `https://raw.githubusercontent.com/ARM-software/CMSIS-DSP/${revision}/`;
function extractFunction(source, name) {
  const start = source.indexOf(`void ${name}(`);
  if (start < 0) throw new Error(`Missing ${name}`);
  const open = source.indexOf('{', start);
  let depth = 1, end = open + 1;
  while (depth && end < source.length) {
    if (source[end] === '{') depth++;
    if (source[end] === '}') depth--;
    end++;
  }
  return 'static ' + source.slice(start, end);
}
function extractTable(source, name, type) {
  const match = source.match(new RegExp(`const ${type} ${name}\\[[^\\]]+\\]\\s*=\\s*\\{([\\s\\S]*?)\\};`));
  if (!match) throw new Error(`Missing table ${name}`);
  if (type === 'uint16_t') return `static const uint16_t ${name}[] = {${match[1]}};`;
  const values = [...match[1].matchAll(/0x([0-9a-f]+)(?:ull|ULL)?/g)].map(m => {
    const buffer = Buffer.alloc(8);
    buffer.writeBigUInt64LE(BigInt('0x' + m[1]));
    const value = buffer.readDoubleLE();
    return Object.is(value, -0) ? '-0.0' : value.toPrecision(17);
  });
  if (values.length !== 4096) throw new Error(`Unexpected table length: ${name}`);
  const lines = [];
  for (let i = 0; i < values.length; i += 4) lines.push('    ' + values.slice(i, i + 4).join(', ') + ',');
  return `static const double ${name}[4096] = {\n${lines.join('\n')}\n};`;
}
(async () => {
  const files = ['Source/TransformFunctions/arm_cfft_f64.c', 'Source/TransformFunctions/arm_rfft_fast_f64.c', 'Source/CommonTables/arm_common_tables.c', 'LICENSE.txt'];
  const downloaded = await Promise.all(files.map(async name => {
    const response = await fetch(base + name);
    if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
    return await response.text();
  }));
  const [cfft, rfft, tables, license] = downloaded;
  const header = cfft.slice(0, cfft.indexOf('#include'));
  const output = path.resolve(__dirname, '../third_party/cmsis-dsp');
  fs.mkdirSync(output, { recursive: true });
  const source = header + `
/* LSAudio modifications: fixed-size forward 4096-point RFFT subset; static
 * helpers; numeric double tables instead of uint64 aliasing; bit-reversal
 * swaps doubles directly. Generated by native/tools/vendor-cmsis.cjs. */
#include <stdint.h>
#include "fft4096.h"
typedef double float64_t;
typedef struct { struct { uint16_t fftLen; } Sint; const double *pTwiddleRFFT; } arm_rfft_fast_instance_f64;
#include "tables.inc"
` + extractFunction(cfft, 'arm_radix4_butterfly_f64') + '\n\n' +
    extractFunction(cfft, 'arm_cfft_radix4by2_f64').replaceAll(', n2,', ', (uint16_t)n2,') + '\n\n' +
    extractFunction(rfft, 'stage_rfft_f64') + `

void lsaudio_rfft4096(double *input, double *output)
{
    const arm_rfft_fast_instance_f64 state = {{2048}, twiddleCoefF64_rfft_4096};
    arm_cfft_radix4by2_f64(input, 2048, twiddleCoefF64_2048);
    for (unsigned i = 0; i < sizeof(armBitRevIndexTableF64_2048) / sizeof(uint16_t); i += 2) {
        unsigned a = armBitRevIndexTableF64_2048[i] >> 2;
        unsigned b = armBitRevIndexTableF64_2048[i + 1] >> 2;
        double value = input[a]; input[a] = input[b]; input[b] = value;
        value = input[a + 1]; input[a + 1] = input[b + 1]; input[b + 1] = value;
    }
    stage_rfft_f64(&state, input, output);
}
`;
  fs.writeFileSync(path.join(output, 'fft4096.c'), source);
  fs.writeFileSync(path.join(output, 'fft4096.h'), '#ifndef LSAUDIO_FFT4096_H\n#define LSAUDIO_FFT4096_H\n/* 4096 doubles per buffer; input is modified, output uses packed RFFT layout. */\nvoid lsaudio_rfft4096(double *input, double *output);\n#endif\n');
  fs.writeFileSync(path.join(output, 'tables.inc'), tables.slice(0, tables.indexOf('#include')) +
    '\n/* Extracted fixed-size tables; uint64 bits converted to exact round-trip decimal doubles. */\n' +
    extractTable(tables, 'twiddleCoefF64_2048', 'uint64_t') + '\n' +
    extractTable(tables, 'twiddleCoefF64_rfft_4096', 'uint64_t') + '\n' +
    extractTable(tables, 'armBitRevIndexTableF64_2048', 'uint16_t') + '\n');
  fs.writeFileSync(path.join(output, 'LICENSE.txt'), license);
  fs.writeFileSync(path.join(output, 'UPSTREAM.md'), `# CMSIS-DSP FFT subset\n\nSource: https://github.com/ARM-software/CMSIS-DSP/tree/${revision}\n\nVersion: v1.14.4. License: Apache-2.0 (see LICENSE.txt).\n\nReproduce with \`node native/tools/vendor-cmsis.cjs\`. Normal builds are offline.\nOnly the forward 4096-point real transform and its tables are included.\n\nModifications: static helper functions; minimal local types; only needed tables;\nuint64 table bits converted to round-trip decimal doubles to avoid strict-aliasing\nand endian assumptions; bit reversal swaps doubles directly.\nNo vendor DLL bytes or disassembled instructions are shipped as code.\n\n## Source SHA-256\n\n` + files.map((name,i)=>`- ${name}: ${crypto.createHash('sha256').update(downloaded[i]).digest('hex')}`).join('\n') + '\n');
  console.log('Vendored pinned CMSIS-DSP forward FFT subset.');
})().catch(error => { console.error(error); process.exitCode = 1; });
