/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconAppExport: typeof import('~icons/app/export')['default']
    IconAppGet: typeof import('~icons/app/get')['default']
    IconAppRConnected: typeof import('~icons/app/r-connected')['default']
    IconAppRConnecting: typeof import('~icons/app/r-connecting')['default']
    IconAppRCross: typeof import('~icons/app/r-cross')['default']
    IconAppRDisconnected: typeof import('~icons/app/r-disconnected')['default']
    IconAppWinMax: typeof import('~icons/app/win-max')['default']
    IconAppWinMin: typeof import('~icons/app/win-min')['default']
    IconAppWinResize: typeof import('~icons/app/win-resize')['default']
    IconAppWrite: typeof import('~icons/app/write')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
