import Vue from 'vue';
import { Button, Select, Autocomplete, Option, Checkbox, Dialog, InputNumber, Input, Slider, MessageBox, Message, Radio, Loading, Form, FormItem } from 'element-ui';
Vue.use(Autocomplete);
Vue.use(Button);
Vue.use(Select);
Vue.use(Option);
Vue.use(Checkbox);
Vue.use(Dialog);
Vue.use(InputNumber);
Vue.use(Input);
Vue.use(Slider);
Vue.use(Radio);
Vue.use(Form);
Vue.use(FormItem);

Vue.use(Loading.directive);
Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$message = Message;